openapi: 3.0.0
info:
  version: "2"
  title: IVMS101 code generator by Sygna Bridge
paths:
  /ivms/example1:
    post:
      description: 'VASP C, on behalf of originator 吴信利 (Xinli Wu), transfers 1 ETH to ABC Limited (trading as CBA Trading), which holds a custodial wallet with VASP D. VASP C routes ETH transfers through the intermediary VASP E.'
      summary: 'Example 1'
      tags:
        - IVMS
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ivms101.Example1'
        required: true
      responses:
        '200':
            description: ''
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ivms101.Status'
                examples:
                  response:
                    value:
                      status: OK
components:
  schemas:
    ivms101.Example1:
      title: Example1
      example:
        originator:
          originatorPersonsList:
          - naturalPerson:
              name:
                nameIdentifiersList:
                - primaryIdentifier: Wu
                  secondaryIdentifier: Xinli
                  nameIdentifierType: LEGL
                - primaryIdentifier: 吳
                  secondaryIdentifier: 信利
                  nameIdentifierType: LEGL
                localNameIdentifiersList: []
                phoneticNameIdentifiersList: []
              geographicAddressesList: []
              nationalIdentification:
                nationalIdentifier: '446005'
                nationalIdentifierType: RAID
                countryOfIssue: ''
                registrationAuthority: RA000553
              customerIdentification: ''
              countryOfResidence: TZ
          accountNumbersList:
          - 1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2
        beneficiary:
          beneficiaryPersonsList:
          - legalPerson:
              name:
                nameIdentifiersList:
                - legalPersonName: ABC Limited
                  legalPersonNameIdentifierType: LEGL
                localNameIdentifiersList: []
                phoneticNameIdentifiersList: []
              geographicAddressesList: []
              customerNumber: ''
              countryOfRegistration: ''
          - legalPerson:
              name:
                nameIdentifiersList:
                - legalPersonName: CBA Trading
                  legalPersonNameIdentifierType: LEGL
                localNameIdentifiersList: []
                phoneticNameIdentifiersList: []
              geographicAddressesList: []
              customerNumber: ''
              countryOfRegistration: ''
          accountNumbersList:
          - 00010190CBATRAD
      properties:
        originator:
          $ref: '#/components/schemas/ivms101.Originator'
        beneficiary:
          $ref: '#/components/schemas/ivms101.Beneficiary'
    ivms101.NaturalPersonNameId:
      title: NaturalPersonNameId
      example:
        primary_identifier: 'Wu'
        secondary_identifier: 'Xinli'
        name_identifier_type: 'NATURAL_PERSON_NAME_TYPE_CODE_LEGL'
      type: object
      properties:
        primary_identifier:
          type: string
        secondary_identifier:
          type: string
        name_identifier_type:
          title: NaturalPersonNameTypeCode
          type: string
          items:
            $ref: "#/components/schemas/ivms101.NaturalPersonNameTypeCode"
    ivms101.LocalNaturalPersonNameId:
      title: LocalNaturalPersonNameId
      example:
        primary_identifier: '吳'
        secondary_identifier: '信利'
        name_identifier_type: 'NATURAL_PERSON_NAME_TYPE_CODE_LEGL'
      type: object
      properties:
        primary_identifier:
          type: string
        secondary_identifier:
          type: string
        name_identifier_type:
          title: NaturalPersonNameTypeCode
          type: string
          items:
            $ref: "#/components/schemas/ivms101.NaturalPersonNameTypeCode"
    ivms101.LocalLegalPersonNameId:
      title: LocalLegalPersonNameId
      example:
        legal_person_name: 'ABC Limited'
        legal_person_name_identifier_type: 'LEGAL_PERSON_NAME_TYPE_CODE_LEGL'
      type: object
      properties:
        legal_person_name:
          type: string
        legal_person_name_identifier_type:
          title: LegalPersonNameTypeCode
          type: string
          items:
            $ref: "#/components/schemas/ivms101.LegalPersonNameTypeCode"
    ivms101.Address:
      title: Address
      example:
        address_type: 'ADDRESS_TYPE_CODE_GEOG'
        street_name: 'Potential Street'
        building_number: '24'
        building_name: 'Weathering Views'
        post_code: '91765'
        town_name: 'Walnut'
        countrySubDivision: 'California'
        country: 'US'
      type: object
      properties:
        address_type:
          title: AddressTypeCode
          type: string
          items:
             $ref: "#/components/schemas/ivms101.AddressTypeCode"
        department:
          type: string
        sub_department:
          type: string
        street_name:
          type: string
        building_number:
          type: string
        building_name:
          type: string
        floor:
          type: string
        post_box:
          type: string
        room:
          type: string
        post_code:
          type: string
        town_name:
          type: string
        town_location_name:
          type: string
        district_name:
          type: string
        country_sub_division:
          type: string
        address_line:
          type: array
          items:
            type: string
        country:
          type: string
    ivms101.NationalIdentification:
      title: NationalIdentification
      example:
        national_identifier: '446005'
        national_identifier_type: 'NATIONAL_IDENTIFIER_TYPE_CODE_RAID'
        registration_authority: 'RA000553'
      type: object
      properties:
        national_identifier:
          type: string
          description: An identifier issued by an appropriate issuing authority
        national_identifier_type:
          title: NationalIdentifierTypeCode
          type: string
          items:
            $ref: '#/components/schemas/ivms101.NationalIdentifierTypeCode'
        country_of_issue:
          type: string
          description: Country of the issuing authority
        registration_authority:
          type: string
          description: A code specifying the registration authority
          # above are belong to type defination
    ivms101.Person:
      title: Person
      type: object
      properties:
        natural_person:
          $ref: "#/components/schemas/ivms101.NaturalPerson"
        legal_person:
          $ref: "#/components/schemas/ivms101.LegalPerson"
    ivms101.NaturalPerson:
      title: NaturalPerson
      type: object
      properties:
        name:
          $ref: "#/components/schemas/ivms101.NaturalPersonName"
        geographic_addresses:
          type: array
          items:
            $ref: "#/components/schemas/ivms101.Address"
        national_identification:
          $ref: "#/components/schemas/ivms101.NationalIdentification"
        customer_identification:
          type: string
        date_and_place_of_birth:
          $ref: "#/components/schemas/ivms101.DateAndPlaceOfBirth"
        country_of_residence:
          type: string
    ivms101.NaturalPersonName:
      title: NaturalPersonName
      example:
        primary_identifier: 'Wu'
        secondary_identifier: 'Xinli'
        name_identifier_type: 'NATURAL_PERSON_NAME_TYPE_CODE_LEGL'
      type: object
      properties:
        name_identifiers:
          type: array
          items:
            $ref: "#/components/schemas/ivms101.NaturalPersonNameId"
        local_name_identifiers:
          type: array
          items:
            $ref: "#/components/schemas/ivms101.LocalNaturalPersonNameId"
        phonetic_name_identifiers:
          type: array
          items:
            $ref: "#/components/schemas/ivms101.LocalNaturalPersonNameId"
    ivms101.DateAndPlaceOfBirth:
      title: DateAndPlaceOfBirth
      description: 'If dateOfBirth is specified, the date specified must be a historic date (i.e. a date prior to the current date)'
      type: object
      properties:
        date_of_birth:
          description: 'Date on which a person is born.'
          type: string
        place_of_birth:
          description: 'The town and/or the city and/or the suburb and/or the country subdivision and/or the country where the person was born.'
          type: string
    ivms101.LegalPerson:
      title: LegalPerson
      type: object
      properties:
        name:
          $ref: "#/components/schemas/ivms101.LegalPersonName"
        geographic_addresses:
          type: array
          items:
            $ref: "#/components/schemas/ivms101.Address"
        customer_number:
          type: string
        national_identification:
          $ref: "#/components/schemas/ivms101.NationalIdentification"
        country_of_registration:
          type: string
    ivms101.LegalPersonName:
      title: LegalPersonName
      type: object
      properties:
        name_identifiers:
          type: array
          items:
            $ref: "#/components/schemas/ivms101.LegalPersonNameId"
        local_name_identifiers:
          type: array
          items:
            $ref: "#/components/schemas/ivms101.LocalLegalPersonNameId"
        phonetic_name_identifiers:
          type: array
          items:
            $ref: "#/components/schemas/ivms101.LocalLegalPersonNameId"
    ivms101.LegalPersonNameId:
      title: LegalPersonNameId
      example:
        legal_person_name: 'CBA Trading'
        legal_person_name_identifier_type: 'LEGAL_PERSON_NAME_TYPE_CODE_TRAD'
      type: object
      properties:
        legal_person_name:
          type: string
        legal_person_name_identifier_type:
          title: LegalPersonNameTypeCode
          type: string
          items:
            $ref: "#/components/schemas/ivms101.LegalPersonNameTypeCode"
    ivms101.IntermediaryVasp:
      title: IntermediaryVasp
      type: object
      properties:
        intermediary_vasp:
          $ref: "#/components/schemas/ivms101.Person"
        sequence:
          type: integer
          minimum: 0
          maximum: 9007199254740991
    ivms101.Originator:
      title: Originator
      type: object
      properties:
        originator_persons:
          type: array
          items:
            $ref: "#/components/schemas/ivms101.Person"
        account_numbers:
          type: array
          items:
            type: string
    ivms101.Beneficiary:
      title: Beneficiary
      type: object
      properties:
        beneficiary_persons:
          type: array
          items:
            $ref: "#/components/schemas/ivms101.Person"
        account_numbers:
          type: array
          items:
            type: string
    ivms101.OriginatingVasp:
      title: OriginatingVasp
      type: object
      properties:
        originating_vasp:
          $ref: "#/components/schemas/ivms101.Person"
    ivms101.BeneficiaryVasp:
      title: BeneficiaryVasp
      type: object
      properties:
        beneficiary_vasp:
          $ref: "#/components/schemas/ivms101.Person"
    ivms101.TransferPath:
      title: TransferPath
      type: object
      properties:
        transfer_path:
          type: array
          items:
            $ref: "#/components/schemas/ivms101.IntermediaryVasp"
    ivms101.PayloadMetadata:
      title: PayloadMetadata
      example:
        transliteration_method: 'TRANSLITERATION_METHOD_CODE_HANI'
      type: object
      properties:
        transliteration_method:
          type: array
          items:
            $ref: "#/components/schemas/ivms101.TransliterationMethodCode"
    ivms101.IdentityPayload:
      title: IdentityPayload
      type: object
      properties:
        originator:
          $ref: "#/components/schemas/ivms101.Originator"
        beneficiary:
          $ref: "#/components/schemas/ivms101.Beneficiary"
        originating_vasp:
          $ref: "#/components/schemas/ivms101.OriginatingVasp"
        beneficiary_vasp:
          $ref: "#/components/schemas/ivms101.BeneficiaryVasp"
        transfer_path:
          $ref: "#/components/schemas/ivms101.TransferPath"
        payload_metadata:
          $ref: "#/components/schemas/ivms101.PayloadMetadata"
    ivms101.NaturalPersonNameTypeCode:
      title: NaturalPersonNameTypeCode
      description: Identifies the nature of the name being specified for a natural person ([IVMS Ref. NaturalPersonNameTypeCode](https://intervasp.org/)).>

              * `ALIA` - Alias name, A name other than the legal name by which a natural person is also known

              * `BIRT` - Name at birth, The name given to a natural person at birth

              * `MAID` - Maiden name, The original name of a natural person who has changed their name after marriage

              * `LEGL` - Legal name, The name that identifies a natural person for legal, official or administrative purposes

              * `MISC` - Unspecified, A name by which a natural person may be known but cannot otherwise be categorized
      type: string
      enum:
        - NATURAL_PERSON_NAME_TYPE_CODE_ALIA
        - NATURAL_PERSON_NAME_TYPE_CODE_BIRT
        - NATURAL_PERSON_NAME_TYPE_CODE_MAID
        - NATURAL_PERSON_NAME_TYPE_CODE_LEGL
        - NATURAL_PERSON_NAME_TYPE_CODE_MISC
    ivms101.LegalPersonNameTypeCode:
      title: LegalPersonNameTypeCode
      description: A single value corresponding to the nature of name being specified for the legal person>
           * `LEGL` - Legal name, Official name under which an organisation is registered
           * `SHRT` - Short name, Specifies the short name of the organisation
           * `TRAD` - Trading name, Name used by a business for commercial purposes, although its registered legal name, used for contracts and other formal situations, may be another
      type: string
      enum:
        - LEGAL_PERSON_NAME_TYPE_CODE_LEGL
        - LEGAL_PERSON_NAME_TYPE_CODE_SHRT
        - LEGAL_PERSON_NAME_TYPE_CODE_TRAD
    ivms101.AddressTypeCode:
      title: AddressTypeCode
      description: ([IVMS Ref. AddressTypeCode](https://intervasp.org/))>

              * `HOME` - Residential, Address is the home address

              * `BIZZ` - Business, Address is the business address

              * `GEOG` - Geographic, Address is the unspecified physical (geographical) address suitable for identification of the natural or legal person
      type: string
      enum:
        - ADDRESS_TYPE_CODE_HOME
        - ADDRESS_TYPE_CODE_BIZZ
        - ADDRESS_TYPE_CODE_GEOG
    ivms101.NationalIdentifierTypeCode:
      title: NationalIdentifierTypeCode
      description: Specifies the type of identifier specified.>
            * `ARNU` - Alien registration number, Number assigned by a government agency to identify foreign nationals.

            * `CCPT` - Passport number, Number assigned by a passport authority.

            * `RAID` - Registration authority identifier, Identifier of a legal entity as maintained by a registration authority.

            * `DRLC` - Driver license number, Number assigned to a driver's license

            * `FIIN` - Foreign investment identity number, Number assigned to a foreign investor number (other than the alien number)

            * `TXID` - Tax identification number, Number assigned by a tax authority to an entity

            * `SOCS` - Social security number, Number assigned by a social security agency

            * `IDCD` - Identity card number, Number assigned by a national authority to an identity card

            * `LEIX` - Legal Entity Identifier, Legal Entity Identifier (LEI) assigned in accordance with ISO 1744211

            * `MISC` - Unspecified, A national identifier which may be known but which cannot otherwise be categorized or the category of which the sender is unable to determine.
      type: string
      enum:
        - NATIONAL_IDENTIFIER_TYPE_CODE_ARNU
        - NATIONAL_IDENTIFIER_TYPE_CODE_CCPT
        - NATIONAL_IDENTIFIER_TYPE_CODE_RAID
        - NATIONAL_IDENTIFIER_TYPE_CODE_DRLC
        - NATIONAL_IDENTIFIER_TYPE_CODE_FIIN
        - NATIONAL_IDENTIFIER_TYPE_CODE_TXID
        - NATIONAL_IDENTIFIER_TYPE_CODE_SOCS
        - NATIONAL_IDENTIFIER_TYPE_CODE_IDCD
        - NATIONAL_IDENTIFIER_TYPE_CODE_LEIX
        - NATIONAL_IDENTIFIER_TYPE_CODE_MISC
    ivms101.TransliterationMethodCode:
      title: TransliterationMethodCode
      type: string
      enum:
        - TRANSLITERATION_METHOD_CODE_ARAB
        - TRANSLITERATION_METHOD_CODE_ARAN
        - TRANSLITERATION_METHOD_CODE_ARMN
        - TRANSLITERATION_METHOD_CODE_CYRL
        - TRANSLITERATION_METHOD_CODE_DEVA
        - TRANSLITERATION_METHOD_CODE_GEOR
        - TRANSLITERATION_METHOD_CODE_GREK
        - TRANSLITERATION_METHOD_CODE_HANI
        - TRANSLITERATION_METHOD_CODE_HEBR
        - TRANSLITERATION_METHOD_CODE_KANA
        - TRANSLITERATION_METHOD_CODE_KORE
        - TRANSLITERATION_METHOD_CODE_THAI
        - TRANSLITERATION_METHOD_CODE_OTHR
    ivms101.Status:
      title: Status
      example:
        status: OK
      type: object
      properties:
        status:
          type: string
      required:
        - status